/// Measurements this repository produces about itself.
///
/// Generated by `tool/generate_build_facts.dart` from `coverage/lcov.info`, a
/// machine-readable test run and the CI workflow — never typed by hand. A page
/// that states its own coverage has to be right about it, and a hard-coded
/// figure is wrong the first time somebody adds a test.
typedef BuildFacts = ({
  String generatedAt,
  double? coveragePercent,
  int? coveredLines,
  int? totalLines,
  int dartTests,
  int workerTests,
  double? lighthousePerformanceFloor,
  double? lighthouseAccessibilityFloor,
});

/// Decodes the generated shape, treating every figure as optional.
///
/// A missing or malformed file yields nulls rather than throwing: the page
/// omits a measurement it does not have instead of failing to render, which
/// is the same posture the content layer takes everywhere else.
BuildFacts parseBuildFacts(Map<String, dynamic> json) => (
  generatedAt: json['generatedAt'] is String
      ? json['generatedAt'] as String
      : '',
  coveragePercent: _double(json['coveragePercent']),
  coveredLines: _int(json['coveredLines']),
  totalLines: _int(json['totalLines']),
  dartTests: _int(json['dartTests']) ?? 0,
  workerTests: _int(json['workerTests']) ?? 0,
  lighthousePerformanceFloor: _double(json['lighthousePerformanceFloor']),
  lighthouseAccessibilityFloor: _double(json['lighthouseAccessibilityFloor']),
);

double? _double(Object? value) => value is num ? value.toDouble() : null;

int? _int(Object? value) => value is num ? value.toInt() : null;
